[project]
name = "genai-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=0.3.27",
    "streamlit>=1.50.0",
    "uv>=0.8.22",
]
